name: Actions

on:
  push:
    branches:
      - '[0-9]+\.[0-9]+\.[0-9]'

jobs:
  frontend-push:
    name: Frontend image Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: front-end-react
          file: ./front-end-react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  order-service-push:
    name: Order service image Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: order-service
          file: ./order-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/order-service:latest
  
  user-service-push:
    name: User service image Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: user-service
          file: ./user-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/user-service:latest

  trigger-cd:
    name: Triggered the Github Action from microapp-deploy to deploy the newest version.
    runs-on: ubuntu-latest
    needs: [frontend-push, order-service-push, user-service-push]
    steps:
      - name: Trigger Workflow in matheoleger/microapp-deploy repository
        run: |
          # Set the required variables
          repo_owner="matheoleger" 
          repo_name="microapp-deploy"  
          event_type="trigger-workflow" 
          service=cicd-project
          version="${{ github.ref_name }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"